### ISSUE TITLE
Add detailed behavior about move/copy

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/specs#130]
- https://github.com/beyondstorage/go-integration-test/issues/26#issuecomment-871228982
- https://matrix.to/#/!l8rnxDAEOzBxO84I:aos.dev/$kD-pxN9A9GvmXeV08qHdo-8bqd2ekCMpcybjrlkXU1g

---

The behavior of move/copy is not clear, we need to add detailed descriptions about them.

**Comment by Xuanwo** [comment]
Does `copy` need to support copy a file to an existing path? aka does `copy` need to be idempotent?

For current `copy` / `move` integration tests https://github.com/beyondstorage/go-integration-test/pull/27, ipfs have to delete files before copy the file: https://github.com/beyondstorage/go-service-ipfs/pull/3/files#diff-8127f6766ba5110c7a99d07305f11d18295fcb2cb08dddb105ab7d55898742c7R16

Maybe we could relax the restriction?

**Comment by JinnyYi** [comment]
For `dropbox`,  copy to an exiting file with `autoreame` false will get `to/conflict/file/` error, but sucecced with `autorename` setting to true and the final file path will be rename with a suffix like `(1)` after original destination path.

**Comment by Xuanwo** [comment]
Tracked in https://github.com/beyondstorage/go-storage/issues/624
