### ISSUE TITLE
Make write Idempotent

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/specs#96]
`Write` will always create files without returned file exists? 

If we made this change, all our API will be Idempotent.

**Comment by JinnyYi** [comment]
Maybe we should change the writemode to `WriteModeOverwrite` in `go-service-dropbox` to overwrite the existing file instead of getting the `path/conflict/file` error?
ref: https://github.com/dropbox/dropbox-sdk-go-unofficial/blob/master/v6/dropbox/files/types.go#L5101-L5124

**Comment by Xuanwo** [comment]
Maybe we could solve this problem together with https://github.com/beyondstorage/specs/issues/130.

Is it possible all API idempotent? (except API like `CreateXxxx`)?

**Comment by JinnyYi** [comment]
> Write will always create files without returned file exists?

I'm confused about `idempotent`. 
As for `write`, I think `write` is idempotent in go-service-*(exclude the services in alpha state, I'm not familiar with them) when multiple requests carry the same centent(In `dropbox`, the conflict occurs in the case where there's a file at the target path with contents different from the contents you're trying to write).

Creating files without returned file exists means overwrite or ignor the error when two `write` requests carry the different content?

**Comment by Xuanwo** [comment]
Tracked in https://github.com/beyondstorage/go-storage/issues/624
