### ISSUE TITLE
Proposal process update

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/specs#99]
We need to update the proposal process to reflect the changes:

- What kind of proposal needs a demo?
- Where the discussion happen?
- What's the relation between proposal and releases?
- How to implement a proposal?

**Comment by xxchan** [comment]
https://github.com/beyondstorage/specs/tree/master/rfcs 
This folder is not ordered by number prefix (but do we need the ordering?), and the RFC list in the README is not maintained.

**Comment by Xuanwo** [comment]
I think the order is not a big problem.

Maybe we can generate the RFC list by scripts?

**Comment by xxchan** [comment]
Or something like the generated sidebar in [Rust RFC website](https://rust-lang.github.io/rfcs/)? 
Btw, personally, I think browsing in the repo is enough. I don't need a full list, but links to related issues/PRs/RFCs is needed.

**Comment by Xuanwo** [comment]
>  Btw, personally, I think browsing in the repo is enough. I don't need a full list, but links to related issues/PRs/RFCs is needed.

It's OK for me to remove the RFC list until someone really has a need for it. Until then, we can consider generating or building a website.

**Comment by Xuanwo** [comment]
Closed for #118 accepted.
